swagger: '2.0'

info:
  title: Stock Info MCP Server
  description: MCP server that provides stock quote and history tools via SSE for integration with Microsoft Copilot Studio.
  version: 1.0.0

host: localhost:3000
basePath: /
schemes:
  - http

paths:
  /sse:
    get:
      summary: MCP Server Actions
      parameters:
        - in: query
          name: sessionId
          type: string
          required: false
      produces:
        - application/json
      responses:
        '200':
          description: Immediate Response
          schema:
            $ref: '#/definitions/QueryResponse'
        '201':
          description: Created and will follow callback
      operationId: InvokeMCP
      tags:
        - Agentic
        - McpSse

  /messages:
    post:
      summary: Post message to MCP server
      description: Sends a JSON-RPC request to the MCP server.
      parameters:
        - name: sessionId
          in: query
          required: true
          type: string
        - in: body
          name: jsonRpcRequest
          required: true
          schema:
            $ref: '#/definitions/QueryResponse'
      responses:
        '200':
          description: Response received
          schema:
            $ref: '#/definitions/QueryResponse'
        '400':
          description: Invalid session or bad request
      operationId: SendMessage
      tags:
        - Agentic
        - McpSse

definitions:
  QueryResponse:
    type: object
    properties:
      jsonrpc:
        type: string
      id:
        type: string
      method:
        type: string
      params:
        type: object
      result:
        type: object
      error:
        type: object

securityDefinitions: {}
security: []
